/**
 * Property-based tests for apps/api/services/walrus-service.ts
 *
 * **Validates: Requirements 3.6, 3.7, 3.8, 3.9, 3.10**
 *
 * Properties tested:
 *
 *   Property 15: Walrus storage round-trip
 *     `digest(walrusGet(walrusPut(b))) == digest(b)` and returned bytes
 *     deep-equal `b`.
 *
 *   Property 16: Walrus integrity verification rejects digest mismatches
 *     For any `(recordedDigest, fetchedBytes)` where
 *     SHA-256(fetchedBytes) ≠ recordedDigest, `walrusGet` with
 *     `expectedDigest` throws `WalrusIntegrityError`.
 *
 *   Property 17: Walrus fetch retry is bounded
 *     For N transient failures followed by success with N ≤ MAX-1, client
 *     issues exactly N+1 calls. For N ≥ MAX, issues exactly MAX calls and
 *     throws `WalrusGetError`.
 *
 *   Bonus — backoff formula invariant:
 *     For all attempt numbers n ≥ 0, `backoffDelayMs(n)` is in [0, 10_000].
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fc from 'fast-check';
import { createHash } from 'node:crypto';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function setEnv(key: string, value: string | undefined) {
  if (value === undefined) {
    delete process.env[key];
  } else {
    process.env[key] = value;
  }
}

// ---------------------------------------------------------------------------
// Import module under test
// ---------------------------------------------------------------------------

import {
  walrusPut,
  walrusGet,
  walrusBlobExists,
  backoffDelayMs,
  sha256Hex,
  WalrusPutError,
  WalrusGetError,
  WalrusIntegrityError,
} from './walrus-service';

// ---------------------------------------------------------------------------
// Environment setup
// ---------------------------------------------------------------------------

const PUBLISHER_URL = 'https://publisher.walrus.test';
const AGGREGATOR_URL = 'https://aggregator.walrus.test';

beforeEach(() => {
  setEnv('WALRUS_PUBLISHER_URL', PUBLISHER_URL);
  setEnv('WALRUS_AGGREGATOR_URL', AGGREGATOR_URL);
  vi.restoreAllMocks();
});

afterEach(() => {
  vi.restoreAllMocks();
});

// ---------------------------------------------------------------------------
// Arbitraries
// ---------------------------------------------------------------------------

/** Generate a non-empty Uint8Array of up to 1024 bytes. */
const arbitraryBytes = fc
  .uint8Array({ minLength: 1, maxLength: 1024 })
  .map((arr) => new Uint8Array(arr));

/** Generate a valid 64-char hex digest string. */
const arbitraryDigest = fc
  .stringMatching(/^[0-9a-f]{64}$/);

/** Generate a blob ID string (alphanumeric, 8–64 chars). */
const arbitraryBlobId = fc.stringMatching(/^[a-zA-Z0-9_-]{8,64}$/);

/** Generate a small attempt count N in [0, MAX_ATTEMPTS-1]. */
const MAX_ATTEMPTS = 5;
const arbitrarySuccessAfterN = fc.integer({ min: 0, max: MAX_ATTEMPTS - 1 });

// ---------------------------------------------------------------------------
// Property 15: Walrus storage round-trip
//
// For all generated byte payloads `b`:
//   - `walrusPut(b)` returns a blobId
//   - `walrusGet(blobId)` returns bytes equal to `b`
//   - `digest(returned bytes) == digest(b)`
//
// We simulate the Walrus network with a mock that stores bytes in memory.
// **Validates: Requirements 3.6**
// ---------------------------------------------------------------------------

describe('Property 15: Walrus storage round-trip', () => {
  it('walrusGet(walrusPut(b)) deep-equals b and digest matches', async () => {
    await fc.assert(
      fc.asyncProperty(arbitraryBytes, async (bytes) => {
        vi.clearAllMocks();

        const originalBytes = new Uint8Array(bytes); // snapshot before any mutation
        const blobId = `blob-${sha256(originalBytes).slice(0, 16)}`;

        // Mock PUT: return a newlyCreated response
        const putResponse = {
          newlyCreated: {
            blobObject: { blobId, size: originalBytes.length },
          },
        };

        // Mock GET: return the stored bytes
        vi.spyOn(globalThis, 'fetch')
          .mockResolvedValueOnce(
            new Response(JSON.stringify(putResponse), { status: 200 }),
          )
          .mockResolvedValueOnce(new Response(new Uint8Array(originalBytes), { status: 200 }));

        const putResult = await walrusPut(new Uint8Array(originalBytes), 1);
        expect(putResult.blobId).toBe(blobId);

        const fetchedBytes = await walrusGet(putResult.blobId, undefined, 1);

        // Round-trip: fetched bytes equal original bytes
        expect(fetchedBytes).toEqual(originalBytes);

        // Digest invariant: digest of fetched bytes equals digest of original
        expect(sha256Hex(fetchedBytes)).toBe(sha256(originalBytes));
      }),
      { numRuns: 10 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 16: Walrus integrity verification rejects digest mismatches
//
// For any `(recordedDigest, fetchedBytes)` where
// SHA-256(fetchedBytes) ≠ recordedDigest, `walrusGet` throws
// `WalrusIntegrityError` and does NOT return the bytes.
//
// **Validates: Requirements 3.7, 3.9**
// ---------------------------------------------------------------------------

describe('Property 16: Walrus integrity verification rejects digest mismatches', () => {
  it('throws WalrusIntegrityError when SHA-256(fetchedBytes) ≠ recordedDigest', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbitraryBytes,
        arbitraryBytes,
        async (bytesA, bytesB) => {
          // Ensure the two byte arrays produce different digests
          fc.pre(sha256(bytesA) !== sha256(bytesB));

          vi.clearAllMocks();

          const recordedDigest = sha256(bytesA); // digest of A
          // Fetch returns B (different bytes → different digest)

          vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
            new Response(new Uint8Array(bytesB), { status: 200 }),
          );

          await expect(
            walrusGet('blob-mismatch', recordedDigest, 1),
          ).rejects.toThrow(WalrusIntegrityError);
        },
      ),
      { numRuns: 10 },
    );
  });

  it('WalrusIntegrityError carries the correct expected and actual digests', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbitraryBytes,
        arbitraryBytes,
        async (bytesA, bytesB) => {
          fc.pre(sha256(bytesA) !== sha256(bytesB));

          vi.clearAllMocks();

          const recordedDigest = sha256(bytesA);
          const actualDigest = sha256(bytesB);

          vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(
            new Response(new Uint8Array(bytesB), { status: 200 }),
          );

          try {
            await walrusGet('blob-check', recordedDigest, 1);
            // Should not reach here
            expect(true).toBe(false);
          } catch (err) {
            expect(err).toBeInstanceOf(WalrusIntegrityError);
            const intErr = err as WalrusIntegrityError;
            expect(intErr.expectedDigest).toBe(recordedDigest);
            expect(intErr.actualDigest).toBe(actualDigest);
          }
        },
      ),
      { numRuns: 10 },
    );
  });

  it('does NOT retry on integrity mismatch (exactly 1 fetch call)', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbitraryBytes,
        arbitraryBytes,
        async (bytesA, bytesB) => {
          fc.pre(sha256(bytesA) !== sha256(bytesB));

          vi.clearAllMocks();

          const recordedDigest = sha256(bytesA);

          const fetchSpy = vi
            .spyOn(globalThis, 'fetch')
            .mockResolvedValue(new Response(new Uint8Array(bytesB), { status: 200 }));

          try {
            await walrusGet('blob-no-retry', recordedDigest, MAX_ATTEMPTS);
          } catch {
            // Expected
          }

          // Integrity mismatch must not trigger retries
          expect(fetchSpy).toHaveBeenCalledTimes(1);
        },
      ),
      { numRuns: 8 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 17: Walrus fetch retry is bounded
//
// For N transient failures (5xx) followed by success with N ≤ MAX-1:
//   - client issues exactly N+1 calls
//   - returns the bytes successfully
//
// For N ≥ MAX transient failures:
//   - client issues exactly MAX calls
//   - throws WalrusGetError
//
// We use fake timers to avoid real sleep delays during retries.
//
// **Validates: Requirements 3.8, 3.10**
// ---------------------------------------------------------------------------

describe('Property 17: Walrus fetch retry is bounded', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  it('issues exactly N+1 calls when N transient failures precede success (N < MAX)', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbitrarySuccessAfterN,
        arbitraryBytes,
        async (n, successBytes) => {
          vi.clearAllMocks();

          const failResponse = new Response('Server Error', { status: 500 });
          const successResponse = new Response(new Uint8Array(successBytes), { status: 200 });

          const fetchSpy = vi.spyOn(globalThis, 'fetch');
          for (let i = 0; i < n; i++) {
            fetchSpy.mockResolvedValueOnce(failResponse);
          }
          fetchSpy.mockResolvedValueOnce(successResponse);

          // Run the operation and advance timers concurrently
          const resultPromise = walrusGet('blob-retry', undefined, MAX_ATTEMPTS);
          await vi.runAllTimersAsync();
          const result = await resultPromise;

          expect(result).toEqual(new Uint8Array(successBytes));
          expect(fetchSpy).toHaveBeenCalledTimes(n + 1);
        },
      ),
      { numRuns: 10 },
    );
  });

  it('issues exactly MAX calls and throws WalrusGetError when all attempts fail', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.constant(MAX_ATTEMPTS),
        async (_n) => {
          vi.clearAllMocks();

          const fetchSpy = vi
            .spyOn(globalThis, 'fetch')
            .mockResolvedValue(new Response('Server Error', { status: 500 }));

          let caughtError: unknown;
          const resultPromise = walrusGet('blob-exhausted', undefined, MAX_ATTEMPTS).catch(
            (e) => { caughtError = e; },
          );
          await vi.runAllTimersAsync();
          await resultPromise;

          expect(caughtError).toBeInstanceOf(WalrusGetError);
          expect(fetchSpy).toHaveBeenCalledTimes(MAX_ATTEMPTS);
        },
      ),
      { numRuns: 5 },
    );
  });

  it('walrusPut: issues exactly N+1 calls when N transient failures precede success', async () => {
    await fc.assert(
      fc.asyncProperty(
        arbitrarySuccessAfterN,
        arbitraryBytes,
        async (n, bytes) => {
          vi.clearAllMocks();

          const blobId = `blob-put-${n}`;
          const failResponse = new Response('Server Error', { status: 500 });
          const successResponse = new Response(
            JSON.stringify({
              newlyCreated: { blobObject: { blobId, size: bytes.length } },
            }),
            { status: 200 },
          );

          const fetchSpy = vi.spyOn(globalThis, 'fetch');
          for (let i = 0; i < n; i++) {
            fetchSpy.mockResolvedValueOnce(failResponse);
          }
          fetchSpy.mockResolvedValueOnce(successResponse);

          const resultPromise = walrusPut(new Uint8Array(bytes), MAX_ATTEMPTS);
          await vi.runAllTimersAsync();
          const result = await resultPromise;

          expect(result.blobId).toBe(blobId);
          expect(fetchSpy).toHaveBeenCalledTimes(n + 1);
        },
      ),
      { numRuns: 10 },
    );
  });

  it('walrusPut: issues exactly MAX calls and throws WalrusPutError when all attempts fail', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.constant(MAX_ATTEMPTS),
        arbitraryBytes,
        async (_n, bytes) => {
          vi.clearAllMocks();

          const fetchSpy = vi
            .spyOn(globalThis, 'fetch')
            .mockResolvedValue(new Response('Server Error', { status: 500 }));

          let caughtError: unknown;
          const resultPromise = walrusPut(new Uint8Array(bytes), MAX_ATTEMPTS).catch(
            (e) => { caughtError = e; },
          );
          await vi.runAllTimersAsync();
          await resultPromise;

          expect(caughtError).toBeInstanceOf(WalrusPutError);
          expect(fetchSpy).toHaveBeenCalledTimes(MAX_ATTEMPTS);
        },
      ),
      { numRuns: 5 },
    );
  });

  it('walrusBlobExists: issues exactly N+1 calls when N transient failures precede success', async () => {
    await fc.assert(
      fc.asyncProperty(arbitrarySuccessAfterN, async (n) => {
        vi.clearAllMocks();

        const failResponse = new Response(null, { status: 500 });
        const successResponse = new Response(null, { status: 200 });

        const fetchSpy = vi.spyOn(globalThis, 'fetch');
        for (let i = 0; i < n; i++) {
          fetchSpy.mockResolvedValueOnce(failResponse);
        }
        fetchSpy.mockResolvedValueOnce(successResponse);

        const resultPromise = walrusBlobExists('blob-exists', MAX_ATTEMPTS);
        await vi.runAllTimersAsync();
        const result = await resultPromise;

        expect(result).toBe(true);
        expect(fetchSpy).toHaveBeenCalledTimes(n + 1);
      }),
      { numRuns: 10 },
    );
  });
});

// ---------------------------------------------------------------------------
// Bonus: backoff formula invariant
//
// For all attempt numbers n ≥ 0, backoffDelayMs(n) ∈ [0, 10_000].
// ---------------------------------------------------------------------------

describe('Backoff formula invariant', () => {
  it('backoffDelayMs(n) is always in [0, 10_000] for any n ≥ 0', () => {
    fc.assert(
      fc.property(fc.integer({ min: 0, max: 100 }), (n) => {
        const delay = backoffDelayMs(n);
        return delay >= 0 && delay <= 10_000;
      }),
      { numRuns: 25 },
    );
  });

  it('backoffDelayMs grows monotonically in base (before cap)', () => {
    // Without jitter, delay(n) = min(2^n * 100, 10_000).
    // With jitter, individual calls may not be monotone, but the base
    // (without jitter) is monotone. We verify the cap is respected.
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 50 }),
        fc.integer({ min: 0, max: 50 }),
        (a, b) => {
          const delayA = backoffDelayMs(a);
          const delayB = backoffDelayMs(b);
          // Both must be within bounds regardless of ordering
          return delayA >= 0 && delayA <= 10_000 && delayB >= 0 && delayB <= 10_000;
        },
      ),
      { numRuns: 25 },
    );
  });
});

// ---------------------------------------------------------------------------
// sha256Hex determinism property
// ---------------------------------------------------------------------------

describe('sha256Hex determinism', () => {
  it('sha256Hex(b) == sha256Hex(b) for all b (deterministic)', () => {
    fc.assert(
      fc.property(
        fc.uint8Array({ minLength: 0, maxLength: 512 }),
        (arr) => {
          const bytes = new Uint8Array(arr);
          return sha256Hex(bytes) === sha256Hex(bytes);
        },
      ),
      { numRuns: 15 },
    );
  });

  it('sha256Hex(a) != sha256Hex(b) when a != b (collision resistance)', () => {
    fc.assert(
      fc.property(
        fc.uint8Array({ minLength: 1, maxLength: 256 }),
        fc.uint8Array({ minLength: 1, maxLength: 256 }),
        (arrA, arrB) => {
          const a = new Uint8Array(arrA);
          const b = new Uint8Array(arrB);
          // Only assert when arrays are actually different
          if (a.length !== b.length || !a.every((v, i) => v === b[i])) {
            return sha256Hex(a) !== sha256Hex(b);
          }
          return true; // same arrays → same digest is correct
        },
      ),
      { numRuns: 15 },
    );
  });
});
