/**
 * apps/api/services/walrus-wallet-bootstrap.ts
 *
 * Bootstraps the Sui CLI and Walrus CLI wallet configuration inside the
 * container at startup, derived from the INFRASTRUCTURE_WALLET_SECRET env var.
 *
 * This ensures the `walrus store` CLI fallback can sign transactions using
 * the same keypair as the primary HTTP publisher path (the infra wallet).
 *
 * SECURITY:
 *   - The private key is read from the environment variable, never logged.
 *   - Key bytes are zeroized after writing to disk.
 *   - Written files have mode 0o600 (user-read-only).
 *   - This function is idempotent — safe to call on every startup.
 *
 * Call order:
 *   1. Called once during server startup (before any request handlers).
 *   2. If the key is missing/invalid, logs a warning — does NOT throw.
 *      The primary HTTP publisher path works without the CLI wallet.
 */

import { writeFile, mkdir, access } from 'node:fs/promises';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { constants } from 'node:fs';

// ---------------------------------------------------------------------------
// Wallet bootstrap
// ---------------------------------------------------------------------------

/**
 * Bootstrap Sui + Walrus CLI wallet config from INFRASTRUCTURE_WALLET_SECRET.
 *
 * If INFRASTRUCTURE_WALLET_SECRET is not set, logs a diagnostic and returns.
 * Failures are non-fatal — the primary HTTP path does not need the CLI wallet.
 */
export async function bootstrapWalrusCLIWallet(): Promise<void> {
  const secret = process.env.INFRASTRUCTURE_WALLET_SECRET;
  if (!secret || secret.trim() === '') {
    console.warn(
      JSON.stringify({
        event: 'walrus_cli_wallet_skip',
        reason: 'INFRASTRUCTURE_WALLET_SECRET not set — CLI fallback will fail if needed',
        timestamp: new Date().toISOString(),
      }),
    );
    return;
  }

  try {
    await writeWalrusConfig();
    await writeSuiConfig(secret.trim());
    console.log(
      JSON.stringify({
        event: 'walrus_cli_wallet_ready',
        timestamp: new Date().toISOString(),
      }),
    );
  } catch (err) {
    // Non-fatal — HTTP publisher is the primary path
    console.warn(
      JSON.stringify({
        event: 'walrus_cli_wallet_bootstrap_failed',
        reason: err instanceof Error ? err.message : String(err),
        timestamp: new Date().toISOString(),
      }),
    );
  }
}

// ---------------------------------------------------------------------------
// Walrus client config
// ---------------------------------------------------------------------------

async function writeWalrusConfig(): Promise<void> {
  const configDir = process.env.WALRUS_CONFIG_PATH
    ? join(process.env.WALRUS_CONFIG_PATH, '..')
    : join(homedir(), '.config', 'walrus');

  const configPath = process.env.WALRUS_CONFIG_PATH
    ?? join(configDir, 'client_config.yaml');

  // Check if config already exists — don't overwrite
  try {
    await access(configPath, constants.F_OK);
    return; // Already exists
  } catch {
    // Doesn't exist — create it
  }

  await mkdir(configDir, { recursive: true });

  // Walrus testnet config
  const config = `# Walrus testnet client config
# Auto-generated by walrus-wallet-bootstrap.ts at startup.
# Do not edit manually — regenerated on container restart.

system_object: 0x6c2547cbbc38025cf3adac45f63cb9a8f3caa4e63e1a04fcfc28ad9e5bc69be6
staking_object: 0x90a7f9e379ac21c82f319a19ad3be1c68a4b12d5da75ef4d88deb49a8ee2b19a

aggregator: ${process.env.WALRUS_AGGREGATOR_URL ?? 'https://aggregator.walrus-testnet.walrus.space'}
publisher: ${process.env.WALRUS_PUBLISHER_URL ?? 'https://publisher.walrus-testnet.walrus.space'}

epochs: ${process.env.WALRUS_EPOCHS ?? '1'}
`;

  await writeFile(configPath, config, { mode: 0o600 });
}

// ---------------------------------------------------------------------------
// Sui keystore config
// ---------------------------------------------------------------------------

/**
 * Write the Sui client.yaml and keystore from the bech32 private key so that
 * the Walrus CLI can sign transactions using the infra wallet.
 */
async function writeSuiConfig(bech32PrivKey: string): Promise<void> {
  const suiConfigDir = join(homedir(), '.sui', 'sui_config');

  // Don't overwrite an existing config
  const clientYaml = join(suiConfigDir, 'client.yaml');
  try {
    await access(clientYaml, constants.F_OK);
    return; // Already configured
  } catch {
    // Not present — proceed
  }

  await mkdir(suiConfigDir, { recursive: true });

  // Decode the bech32 private key to extract the raw key bytes for the keystore
  // Format: bech32-encoded "suiprivkey1..." → base64 keystore entry
  let keystoreEntry: string;
  try {
    const { decodeSuiPrivateKey } = await import('@mysten/sui/cryptography');
    const { Ed25519Keypair } = await import('@mysten/sui/keypairs/ed25519');

    const { secretKey } = decodeSuiPrivateKey(bech32PrivKey);
    const keypair = Ed25519Keypair.fromSecretKey(secretKey);
    const address = keypair.toSuiAddress();

    // Sui keystore format: base64-encoded [scheme_flag (1 byte) | secret_key (32 bytes)]
    // ED25519 scheme flag = 0x00
    const keystoreBytes = new Uint8Array(33);
    keystoreBytes[0] = 0x00; // ED25519
    keystoreBytes.set(secretKey, 1);
    keystoreEntry = Buffer.from(keystoreBytes).toString('base64');

    // Zeroize sensitive bytes
    secretKey.fill(0);
    keystoreBytes.fill(0);

    // Write keystore file
    const keystorePath = join(suiConfigDir, 'sui.keystore');
    await writeFile(
      keystorePath,
      JSON.stringify([keystoreEntry]),
      { mode: 0o600 },
    );

    // Write client.yaml pointing to testnet
    const rpcUrl = process.env.SUI_RPC_URL ?? 'https://fullnode.testnet.sui.io:443';
    const clientConfig = `---
keystore:
  File: ${keystorePath}
envs:
  - alias: testnet
    rpc: "${rpcUrl}"
    ws: ~
    basic_auth: ~
active_env: testnet
active_address: "${address}"
`;

    await writeFile(clientYaml, clientConfig, { mode: 0o600 });
  } catch (keyErr) {
    // Don't log anything that might contain key material
    throw new Error(
      `Failed to write Sui config: ${keyErr instanceof Error ? keyErr.message : 'unknown error'}`,
    );
  }
}
